name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - name: Download Dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run the tests
        run: npm run test
